server:
  port: 9081
  servletPath: /monitor
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
# Local git repository: Run requisites 1
          uri: file:///${user.home}/server-config
# From GitHub Run requisites 3
#          uri: https://github.com/your-username/your-config-repo.git
#            username: your-username
#            password: ${GITHUB_ACCESS_TOKEN}
# Using SSH keys: you must add ssh key to Git Server and to your server Run requisites 2
#          uri: https://github.com/your-username/your-config-repo.git
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 25
    service-url:
      defaultZone: http://discUser:discPassword@localhost:9761/eureka/
  instance:
    statusPageUrlPath: ${server.servletPath}/info
    healthCheckUrlPath: ${server.servletPath}/health
# Https options
#  instance:
#    nonSecurePortEnabled: false
#    securePortEnabled: true
#    statusPageUrl: https://${eureka.hostname}/info
#    healthCheckUrl: https://${eureka.hostname}/health
#    homePageUrl: https://${eureka.hostname}/